[terminal.shell]
args = ["-l", "-c", "tmux new-session -A -s main"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1

[window.padding]
x = 4
y = 4

[font]
size = 13

[font.normal]
family = "Monaspace Argon"
style = "Regular"

[font.bold]
family = "Monaspace Argon"
style = "Bold"

[font.italic]
family = "Monaspace Argon"
style = "Italic"

[colors]
[colors.primary]
background = "0x282828"
foreground = "0xeeeeee"
[colors.normal]
black = "0x282828"
red = "0xf43753"
green = "0xc9d05c"
yellow = "0xffc24b"
blue = "0xb3deef"
magenta = "0xd3b987"
cyan = "0x73cef4"
white = "0xeeeeee"
[colors.bright]
black = "0x4c4c4c"
red = "0xf43753"
green = "0xc9d05c"
yellow = "0xffc24b"
blue = "0xb3deef"
magenta = "0xd3b987"
cyan = "0x73cef4"
white = "0xfeffff"

[terminal]
